[workspace]
members = [
    "src/papyrus",
	"src/revdb",
]

[patch.crates-io]
papyrus = { path = "src/papyrus" }
revdb = { path = "src/revdb" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
