name: Testing

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
      - stage

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 64
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install packages
        run: |
          pip install poetry
          poetry config virtualenvs.create false --local
          poetry install
      - name: run testing
        run: |
          poetry run pytest -n auto --cov=src/papyrus --no-cov-on-fail --benchmark-skip
          poetry run pytest --benchmark-only --benchmark-name=short --benchmark-columns=min,mean,max,ops,outliers
